dist: xenial
sudo: required
language: python
python:
  - '2.7'

before_install:
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop
  - cp states/vars.template states/vars

script:
  - sudo salt-call --local --file-root=./states state.highstate --retcode-passthrough
